---
title: Kid's Cup of Rochester
timezone: UTC
collections:
  posts:
    title: Posts
    output: true
  uploads:
    title: Uploads
    output: true
email: kidscuprochester@gmail.com
description: Kid's Cup Rochester Golf Tournament
baseurl: "/"
url: https://kidscuprochester.github.io
markdown: kramdown
plugins:
- jekyll-feed
intro:
  image: "/uploads/Somerby.jpg"
quick_actions:
  want_to_golf:
    button_text: I want to golf
    button_link: https://secure.ministrysync.com/ministrysync/event/?e=19294
  want_to_donate:
    button_text: I want to donate
    button_link: https://secure.ministrysync.com/ministrysync/event/?e=19294
  want_to_sponsor:
    button_text: I want to sponsor
    button_link: mailto:marge.kelley@expresspros.com?subject=Kid's Cup Rochester Sponsorship&body=I%20would%20like%20to%20be%20a%20Kid's%20Cup%20sponsor!
  want_to_purchase_tickets:
    button_text: I want to buy tickets
    button_link: mailto:marge.kelley@expresspros.com?subject=Kid's Cup Rochester Tickets&body=I%20would%20like%20to%20purchase%20tickets%20to%20the%20Kid's%20Cup%20Social%20Hour%20and%20Dinner!
next_event:
  date: 2021-05-24 10:30:00.000000000 Z
  time: 10:30 - 5:00 PM
  location: Somerby Golf Club
  directions_url: https://www.google.com/maps/dir//''/@44.0477542,-92.6697751,13z/data=!4m8!4m7!1m0!1m5!1m1!1s0x87f742b8acef5c79:0xe0c57d3c2c3b35dd!2m2!1d-92.6347557!2d44.0476979
who_we_are:
  text: |-
    The corona virus pandemic has affected every one of us in our community and it’s a public health crisis that requires collective action. With the uncertainty of the health crisis, we have made the decision to move forward with the 2021 Kid’s Cup Golf Tournament but in a slightly different format than prior years.

    We are excited for the opportunity to come together as a community to raise money for so many kids and their families.  We will be following CDC, Mayo Clinic and Olmsted Medical Center Covid-19 protocols to continue to do our part to reduce exposure and keep our community safe.

    We look forward to seeing you at the 24th Annual Kid’s Cup Golf Tournament May 24, 2021.

    For questions, please contact Marge Kelley, marge.kelley@expresspros.com
  image: "/uploads/Team%20High%20Five-54a5d6.jpg"
whats_new:
  text: "The tournament will be held at [Somerby Golf Club](http://www.somerby.com),
    South East Minnesota's premiere championship golf club, on May 24, 2021.\nThe
    tournament will be 18 holes with lunch on the course.  More information will be
    available soon regarding the auction and ways to stay involved.  \n\n"
  image: "/uploads/Somerby.jpg"
sign_up:
  for_golfers:
    text: 'Registration is easy. Simply create your fund easy page [here](https://secure.ministrysync.com/ministrysync/event/website/home/?e=19294).
      Once registered, you can direct potential donors to your site and share the
      link on Facebook and Twitter.  If you receive donations as cash or check, simply
      record the donations on your Fund Easy page, and contact Marge.Kelley@Expresspros.com
      for direction for cash or check collection prior to the event.   '
    button_link: https://secure.ministrysync.com/ministrysync/event/?e=19294
    button_text: I want to give!
  for_sponsors:
    text: 'We understand that not everyone is a golfer. However, there are sponsorship
      opportunities available, along with volunteer opportunities. For more information
      contact Jeff Jensen ([jeff.jensen@expresspros.com](mailto:jeff.jensen@expresspros.com?subject=Kid''s
      Cup Rochester Sponsorship)) or Marge Kelley ([marge.kelley@expresspros.com](mailto:marge.kelley@expresspros.com?subject=Kid''s
      Cup Rochester Sponsorship)). '
    button_link: mailto:marge.kelley@expresspros.com?subject=Kid's Cup Rochester Sponsorship
    button_text: I want to sponsor!
presenting_sponsors:
- image: "/uploads/express_logo.png"
  name: Express Employment Professionals
  link: https://www.expresspros.com/
- image: "/uploads/EWP_Cobrand-f4e522.png"
  name: Echelon Wealth Partners
  link: https://www.ameripriseadvisors.com/team/echelon-wealth-partners
corporate_sponsors:
- image: "/uploads/somerby_logo.jpg"
  name: Somerby Golf Club
  link: http://www.somerby.com/
- image: "/uploads/Trina%20logo%202020.JPG"
  name: Trina Solano, Realtor
  link: https://www.edinarealty.com/trina-solano-realtor#/
- image: "/uploads/sams_club_logo.png"
  name: Sam's Club
  link: https://samsclub.com
other_sponsors:
- image: "/uploads/First-Security-Bank-Byron-d05fe7.png"
  name: First Security Bank Byron
  link: https://www.fsbbyron.com/
- image: "/uploads/Morris%20Concrete.png"
  name: Morris Concrete, Inc.
  link: https://www.facebook.com/pages/Morris-Concrete/164999316859681
- image: "/uploads/Ames%20Construction.JPG"
  name: Ames Construction
  link: https://www.amesconstruction.com/
- image: "/uploads/Sola.png"
  name: Sola Salon Studios
  link: https://www.solasalonstudios.com
marketing_sponsors:
- image: "/uploads/pro_image_logo.png"
  name: Pro Image
  link: http://www.proimageroch.com
- image: "/uploads/Capture.JPG"
  name: Johnson Printing
  link: http://www.johnson-printing.com/
- image: "/uploads/iheart_media_logo.png"
  name: iHeart Media
  link: https://www.iheartmedia.com/iheartmedia/stations?city=Rochester
- image: "/uploads/KIMT%20Logo%20-%20HQ%20.png"
  name: KIMT News 3
  link: https://www.kimt.com
